version: "3.8"

services:
  postgres:
    image: ${DOCKER_REGISTRY-}postgres
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce
    build:
      context: .
      dockerfile: Ecommerce.Infraestructure.Data/Dockerfile

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: postgres-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ivansantiagovb@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ecommerce

  ecommerce.services.webapi:
    image: ${DOCKER_REGISTRY-}ecommerceserviceswebapi
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Ecommerce.Services.WebApi/Dockerfile
    networks:
      - ecommerce

networks:
  ecommerce:
    name: ecommerce
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
